AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 200

Metrics/ModuleLength:
  Max: 120

Metrics/MethodLength:
  Max: 250

Metrics/BlockLength:
  Max: 250

Metrics/ClassLength:
  Max: 300

Metrics/AbcSize:
  Max: 35

Layout/AccessModifierIndentation:
  EnforcedStyle: indent
  
Layout/IndentationWidth:
  Width: 2

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods