version: "3.3"
services:
  db:
    image: postgres:12.2
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    env_file:
      - .env_prod
  telegram:
    build: .
    command: bash -c "exe/chatgpt_bot telegram"
    volumes:
      - .:/chatgpt_assistant
    environment:
      POSTGRES_HOST: db
    env_file:
      - .env_prod
    depends_on:
      - db
  discord:
    build: .
    command: bash -c "exe/chatgpt_bot discord"
    volumes:
      - .:/chatgpt_assistant
    environment:
      POSTGRES_HOST: db
    env_file:
      - .env_prod
    depends_on:
      - db
volumes:
  postgres: