version: "3.3"
services:
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
  db:
    image: postgres:12.2
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    env_file:
      - .env
  telegram:
    build: .
    command: bash -c "exe/chatgpt_bot telegram"
    volumes:
      - .:/assistant
    environment:
      POSTGRES_HOST: db
    env_file:
      - .env
    depends_on:
      - db
  discord:
    build: .
    command: bash -c "exe/chatgpt_bot discord"
    volumes:
      - .:/assistant
    environment:
      POSTGRES_HOST: db
    env_file:
      - .env
    depends_on:
      - db
  sidekiq:
    build: .
    command: bash -c "exe/chatgpt_bot sidekiq"
    volumes:
      - .:/assistant
    environment:
      POSTGRES_HOST: db
    env_file:
      - .env
    depends_on:
      - db
      - redis
volumes:
  postgres:
