version: "3.3"
services:
  db:
    image: postgres:12.2
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    env_file:
      - .env
  bot:
    build: .
    command: bash -c "exe/bot start"
    volumes:
      - .:/telegram_chatgpt
    environment:
      POSTGRES_HOST: db
    env_file:
      - .env
    depends_on:
      - db
volumes:
  postgres: